(() => {
  'use strict';
  const $ = (key) => document.querySelector(`[data-doc="${key}"]`);
  const dom = { form: $('upload-form'), input: $('file-input'), ocr: $('ocr'), queue: $('queue'), selected: $('selected-file'), status: $('status'), table: $('table'), count: $('count'), reindex: $('reindex'), zone: $('drop-zone'), upload: $('upload'), removeQueued: $('remove-queued'), removeLibrary: $('remove-library'), preview: $('preview'), previewTitle: $('preview-title'), previewMeta: $('preview-meta'), previewText: $('preview-text'), closePreview: $('close-preview') };
  let queue = [], librarySelection = new Set();
  const escapeHTML = (value) => { const box = document.createElement('div'); box.textContent = value || ''; return box.innerHTML; };
  const formatSize = (bytes) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  const setStatus = (message, type = '') => { dom.status.textContent = message; dom.status.className = `upload-status ${type}`; };
  const today = () => new Date().toISOString().slice(0, 10);
  async function request(url, options = {}) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Không thể hoàn tất yêu cầu.'); return data; }
  function updateSelected() { dom.selected.textContent = queue.length ? `${queue.length} tệp trong hàng đợi` : 'Chưa chọn tệp'; dom.upload.disabled = !queue.length; dom.removeQueued.disabled = !queue.some((item) => item.selected); }
  function renderQueue() {
    dom.queue.innerHTML = queue.length ? `<h3>Hàng đợi tải lên</h3>${queue.map((item) => `<article class="queue-item"><label><input data-queue-select="${item.id}" type="checkbox" ${item.selected ? 'checked' : ''}> Chọn</label><strong>${escapeHTML(item.file.name)}</strong><small>${formatSize(item.file.size)}</small><div class="queue-fields"><label>STT<input data-queue-field="order" data-queue-id="${item.id}" type="number" min="1" value="${escapeHTML(item.order)}"></label><label>Số quyết định<input data-queue-field="decision_number" data-queue-id="${item.id}" value="${escapeHTML(item.decision_number)}"></label><label>Điều / khoản<input data-queue-field="article_clause" data-queue-id="${item.id}" value="${escapeHTML(item.article_clause)}"></label><label>Ngày áp dụng<input data-queue-field="document_date" data-queue-id="${item.id}" type="date" value="${escapeHTML(item.document_date)}"></label><label class="queue-ocr"><input data-queue-field="ocr" data-queue-id="${item.id}" type="checkbox" ${item.ocr ? 'checked' : ''}> OCR</label></div></article>`).join('')}` : '';
    dom.queue.querySelectorAll('[data-queue-select]').forEach((input) => input.addEventListener('change', () => { queue.find((entry) => entry.id === input.dataset.queueSelect).selected = input.checked; updateSelected(); }));
    dom.queue.querySelectorAll('[data-queue-field]').forEach((input) => input.addEventListener('change', () => { const item = queue.find((entry) => entry.id === input.dataset.queueId); item[input.dataset.queueField] = input.type === 'checkbox' ? input.checked : input.value; }));
    updateSelected();
  }
  function addFiles(files) { for (const file of files) { if (!/\.(pdf|docx|png|jpe?g|webp)$/i.test(file.name) || file.size > 25 * 1024 * 1024) { setStatus(`${file.name}: chỉ nhận PDF/DOCX/PNG/JPG/WEBP, tối đa 25 MB.`, 'error'); continue; } queue.push({ id: `${Date.now()}-${Math.random()}`, file, selected: false, order: String(queue.length + 1), decision_number: '', article_clause: '', document_date: today(), ocr: dom.ocr.checked }); } dom.input.value = ''; renderQueue(); }
  function metadataLine(item) { return [item.order && `STT ${item.order}`, item.decision_number && `QĐ ${item.decision_number}`, item.article_clause, item.document_date, item.ocr && 'OCR'].filter(Boolean).join(' · '); }
  async function load() {
    const items = await request('/api/documents'), uploads = items.filter((item) => item.kind === 'uploaded');
    dom.count.textContent = `${uploads.length} tài liệu tải lên · ${items.length} nguồn đã lập chỉ mục`;
    dom.table.innerHTML = items.map((item) => `<tr><td>${item.kind === 'uploaded' ? `<input data-library-select="${item.id}" type="checkbox" ${librarySelection.has(item.id) ? 'checked' : ''}>` : ''}</td><td><strong>${escapeHTML(item.title)}</strong><small>${escapeHTML(item.filename || item.rid)}${item.size ? ` · ${formatSize(item.size)}` : ' · Dữ liệu minh họa'} · ${item.chunk_count || 0} đoạn truy xuất${metadataLine(item) ? `<br>${escapeHTML(metadataLine(item))}` : ''}</small></td><td>${escapeHTML(item.format || 'DATA')}</td><td><span class="status-tag ${item.status === 'ready' ? 'ready' : 'demo'}">${item.kind === 'uploaded' ? (item.ocr ? 'Đã OCR & chuẩn hóa' : 'Đã chuẩn hóa') : 'Minh họa'}</span></td><td>${item.uploaded_at ? new Date(item.uploaded_at).toLocaleString('vi-VN') : escapeHTML(item.valid_from || '')}</td><td>${item.kind === 'uploaded' ? `<button class="delete-button" data-preview="${item.id}">Xem nội dung</button> <button class="delete-button" data-delete="${item.id}">Xóa</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="6">Chưa có tài liệu.</td></tr>';
    dom.table.querySelectorAll('[data-library-select]').forEach((input) => input.addEventListener('change', () => { input.checked ? librarySelection.add(input.dataset.librarySelect) : librarySelection.delete(input.dataset.librarySelect); dom.removeLibrary.disabled = !librarySelection.size; }));
    dom.table.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', () => deleteDocuments([button.dataset.delete])));
    dom.table.querySelectorAll('[data-preview]').forEach((button) => button.addEventListener('click', () => preview(button.dataset.preview)));
    dom.removeLibrary.disabled = !librarySelection.size;
  }
  async function deleteDocuments(ids) { if (!ids.length || !confirm(`Xóa ${ids.length} tài liệu đã chọn khỏi cơ sở tri thức?`)) return; try { for (const id of ids) await request(`/api/documents/${id}`, { method: 'DELETE' }); ids.forEach((id) => librarySelection.delete(id)); setStatus('Đã xóa tài liệu và cập nhật chỉ mục.', 'success'); await load(); } catch (error) { setStatus(error.message, 'error'); } }
  async function preview(id) { try { const data = await request(`/api/documents/${id}/text`); dom.previewTitle.textContent = data.title; dom.previewMeta.textContent = `${data.chunk_count || 0} đoạn truy xuất · văn bản đã trích xuất`; dom.previewText.textContent = data.text; dom.preview.hidden = false; dom.preview.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (error) { setStatus(error.message, 'error'); } }
  dom.input.addEventListener('change', () => addFiles([...dom.input.files]));
  ['dragenter', 'dragover'].forEach((event) => dom.zone.addEventListener(event, (e) => { e.preventDefault(); dom.zone.classList.add('dragging'); }));
  ['dragleave', 'drop'].forEach((event) => dom.zone.addEventListener(event, (e) => { e.preventDefault(); dom.zone.classList.remove('dragging'); }));
  dom.zone.addEventListener('drop', (event) => addFiles([...event.dataTransfer.files]));
  dom.removeQueued.addEventListener('click', () => { queue = queue.filter((item) => !item.selected); renderQueue(); });
  dom.removeLibrary.addEventListener('click', () => deleteDocuments([...librarySelection]));
  dom.closePreview.addEventListener('click', () => { dom.preview.hidden = true; });
  dom.form.addEventListener('submit', async (event) => { event.preventDefault(); if (!queue.length) return; dom.upload.disabled = true; let done = 0; try { for (const item of [...queue]) { setStatus(`Đang xử lý ${done + 1}/${queue.length}: ${item.file.name}`); const body = new FormData(); body.append('file', item.file); body.append('ocr', item.ocr ? 'true' : 'false'); for (const key of ['order', 'decision_number', 'article_clause', 'document_date']) body.append(key, item[key]); await request('/api/documents/upload', { method: 'POST', body }); queue = queue.filter((entry) => entry.id !== item.id); done += 1; renderQueue(); } setStatus(`Đã tải lên và lập chỉ mục ${done} tài liệu.`, 'success'); await load(); } catch (error) { setStatus(`${done} tệp đã xong. ${error.message}`, 'error'); } finally { dom.upload.disabled = !queue.length; } });
  dom.reindex.addEventListener('click', async () => { dom.reindex.disabled = true; setStatus('Đang xây dựng lại chỉ mục...'); try { const result = await request('/api/documents/reindex', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); setStatus(`Đã lập chỉ mục ${result.documents} tài liệu với ${result.chunks} đoạn nội dung.`, 'success'); await load(); } catch (error) { setStatus(error.message, 'error'); } finally { dom.reindex.disabled = false; } });
  renderQueue(); load().catch((error) => setStatus(error.message, 'error'));
})();
